###
# @name fetch_db_data
@country = "Indonesia"
POST http://{{host}}:{{port}}/db
Content-Type: application/json

{
    "country": {{country}}
}
###

###
# @name get_job_status
@uuid =f31c4c2b-7a52-45ea-a24c-0ce0f3525b16
GET http://{{host}}:{{port}}/db
    ?event_id={{uuid}}  
###

