
@host=127.0.0.1
@port=8080


###
# @name fetch_db_data
@country = "Indonesia"
POST http://{{host}}:{{port}}/db
Content-Type: application/json

{
    "country": {{country}}
}
###

###
# @name get_job_status
@uuid = 20f38377-3184-4c29-b016-06efa96aa355
GET http://{{host}}:{{port}}/db
    ?event_id={{uuid}}  
###

